"""Configure cascade deleting where it was shoud be

Revision ID: 2522d2494165
Revises: e0f4dff0bf61
Create Date: 2025-06-05 19:02:42.786364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2522d2494165'
down_revision: Union[str, None] = 'e0f4dff0bf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_user_id_fkey'), 'order', type_='foreignkey')
    op.drop_constraint(op.f('order_ticker_fkey'), 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.drop_constraint(op.f('order_book_level_ticker_fkey'), 'order_book_level', type_='foreignkey')
    op.create_foreign_key(None, 'order_book_level', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.drop_constraint(op.f('transaction_ticker_fkey'), 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_ticker_fkey'), 'transaction', 'instrument', ['ticker'], ['ticker'])
    op.drop_constraint(None, 'order_book_level', type_='foreignkey')
    op.create_foreign_key(op.f('order_book_level_ticker_fkey'), 'order_book_level', 'instrument', ['ticker'], ['ticker'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(op.f('order_ticker_fkey'), 'order', 'instrument', ['ticker'], ['ticker'])
    op.create_foreign_key(op.f('order_user_id_fkey'), 'order', 'user_account', ['user_id'], ['id'])
    # ### end Alembic commands ###
