"""Fix bug

Revision ID: 57eb46a3b808
Revises: 72c07921a769
Create Date: 2025-06-05 19:20:40.310706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57eb46a3b808'
down_revision: Union[str, None] = '72c07921a769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balance_user_id_fkey'), 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key(op.f('balance_user_id_fkey'), 'balance', 'user_account', ['user_id'], ['id'])
    # ### end Alembic commands ###
