"""Fix deleting

Revision ID: 74d89507ae3a
Revises: fe4d0cd4b0e2
Create Date: 2025-06-05 18:56:05.123502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d89507ae3a'
down_revision: Union[str, None] = 'fe4d0cd4b0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balance_ticker_fkey'), 'balance', type_='foreignkey')
    op.create_foreign_key(None, 'balance', 'instrument', ['ticker'], ['ticker'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.create_foreign_key(op.f('balance_ticker_fkey'), 'balance', 'instrument', ['ticker'], ['ticker'])
    # ### end Alembic commands ###
