version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: backend/database/Dockerfile
    env_file:
      - config/.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    volumes:
      - ..:/app
volumes:
  postgres_data: